# Generated by Django 5.0.2 on 2024-03-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='major_mvp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='major_winner',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='surname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='team',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
