# Generated by Django 5.0.2 on 2024-03-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_alter_players_age_alter_players_major_mvp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='major_mvp',
            new_name='major_MVP',
        ),
        migrations.AddField(
            model_name='players',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
