# Generated by Django 5.0.2 on 2024-03-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_rename_major_mvp_players_major_mvp_players_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='full_player_name',
            field=models.CharField(blank=True, default='player', max_length=90, null=True),
        ),
    ]
