# Generated by Django 5.0.2 on 2024-03-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_players_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='weapon',
            field=models.CharField(blank=True, default='Rifler', max_length=60, null=True),
        ),
    ]
