# Generated by Django 5.0.2 on 2024-03-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_players_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='major_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='players',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='players',
            name='country',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='players',
            name='full_player_name',
            field=models.CharField(default='player', max_length=90),
        ),
        migrations.AlterField(
            model_name='players',
            name='major_MVP',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='players',
            name='major_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='players',
            name='region',
            field=models.CharField(default='Earth', max_length=90),
        ),
        migrations.AlterField(
            model_name='players',
            name='surname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='players',
            name='team',
            field=models.CharField(default='No team', max_length=30),
        ),
        migrations.AlterField(
            model_name='players',
            name='weapon',
            field=models.CharField(default='Rifler', max_length=60),
        ),
    ]
