COUNTRY_REGIONS = {
    "CIS Region": ["Russia", "Ukraine", "Belarus", "Kazakhstan", "Moldova", "Azerbaijan", "Armenia", "Georgia",
                   "Kyrgyzstan", "Tajikistan", "Turkmenistan", "Uzbekistan"],
    "Australia and Oceania": ["Australia", "New Zealand", "Fiji", "Papua New Guinea", "Samoa", "Tonga", "Vanuatu",
                              "Micronesia", "Marshall Islands", "Palau", "Tuvalu", "Nauru", "Kiribati"],
    "North America": ["United States", "Canada", "Mexico", "Cuba", "Jamaica", "Haiti", "Dominican Republic",
                      "Guatemala", "Honduras", "El Salvador", "Nicaragua", "Costa Rica", "Panama", "Belize"],
    "South America": ["Brazil", "Argentina", "Peru", "Colombia", "Venezuela", "Ecuador", "Chile", "Bolivia", "Paraguay",
                      "Uruguay", "Guyana", "Suriname"],
    "Europe": ["United Kingdom", "Germany", "France", "Italy", "Spain", "Poland", "Netherlands", "Belgium",
               "Switzerland", "Sweden", "Austria", "Norway", "Denmark", "Finland", "Greece", "Czech Republic",
               "Portugal", "Hungary", "Romania", "Ireland", "Slovakia", "Croatia", "Bosnia and Herzegovina", "Estonia",
               "Lithuania", "Latvia", "Slovenia", "Montenegro", "North Macedonia", "Kosovo", "Serbia", "Albania",
               "Andorra", "Monaco", "San Marino", "Vatican City"],
    "Asia": ["China", "Turkey", "Israel", "India", "Indonesia", "Pakistan", "Bangladesh", "Japan", "Philippines",
             "Vietnam",
             "Thailand", "Myanmar", "South Korea", "Afghanistan", "Saudi Arabia", "Malaysia", "Yemen", "Nepal",
             "North Korea", "Sri Lanka", "Syria", "Cambodia", "Jordan", "United Arab Emirates", "Laos", "Lebanon",
             "Singapore", "Oman", "State of Palestine", "Kuwait", "Mongolia", "Qatar", "Bahrain", "Timor-Leste",
             "Bhutan", "Maldives", "Brunei"],
    "Africa": ["Nigeria", "Ethiopia", "Egypt", "Democratic Republic of the Congo", "Tanzania", "South Africa", "Kenya",
               "Uganda", "Algeria", "Sudan", "Morocco", "Angola", "Mozambique", "Ghana", "Madagascar", "Cameroon",
               "Côte d'Ivoire", "Niger", "Burkina Faso", "Mali", "Malawi", "Zambia", "Senegal", "Chad", "Somalia",
               "Zimbabwe", "Guinea", "Rwanda", "Benin", "Burundi", "Tunisia", "South Sudan", "Togo", "Sierra Leone",
               "Libya", "Congo", "Liberia", "Central African Republic", "Mauritania", "Eritrea", "Namibia", "Gambia",
               "Botswana", "Gabon", "Lesotho", "Guinea-Bissau", "Equatorial Guinea", "Mauritius", "Eswatini",
               "Djibouti", "Comoros", "Cabo Verde", "Sao Tome and Principe", "Seychelles"]
}