# Generated by Django 5.0.2 on 2024-03-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userconfirmcodehelp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserConfirmCodeHelp',
            new_name='EmailConfirmCodeHelperForm',
        ),
    ]
