# Generated by Django 5.0.2 on 2024-03-02 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailconfirmcodehelpermodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmcodehelpermodel',
            name='deletion_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 14, 0, 11, 595451, tzinfo=datetime.timezone.utc)),
        ),
    ]
