# Generated by Django 5.0.2 on 2024-03-17 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_emailconfirmcodehelpermodel_deletion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quizzes_lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='quizzes_win',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailconfirmcodehelpermodel',
            name='deletion_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 15, 29, 31, 5456, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
