# Generated by Django 4.2.11 on 2024-03-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_quizzes_lose_user_quizzes_win_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfirmCodeHelperModel',
        ),
    ]
