# Generated by Django 5.0.2 on 2024-03-15 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_emailconfirmcodehelpermodel_deletion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmcodehelpermodel',
            name='deletion_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 17, 18, 44, 816517, tzinfo=datetime.timezone.utc)),
        ),
    ]
