# Generated by Django 5.0.2 on 2024-03-08 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_emailconfirmcodehelpermodel_deletion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmcodehelpermodel',
            name='deletion_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 12, 32, 11, 927785, tzinfo=datetime.timezone.utc)),
        ),
    ]
